package com.example.demo.model;

public enum MovieGenre {
    ADVENTURE, ACTION, COMEDY, CRIME, DRAMA, FANTASY, HISTORICAL, HORROR,
    PSYCHOLOGICAL_THRILLER, ROMANCE, SCIENCE_FICTION, THRILLER, WESTERN

}
