package com.example.demo;

public enum MovieGenre {
    ADVENTURE, ACTION, COMEDY, CRIME, DRAMA, FANTASY, HISTORICAL, HORROR,
    PSYCHOLOGICAL_THRILLER, ROMANCE, SCIENCE_FICTION, THRILLER, WESTERN, ANIMATION, FAMILY, MUSIC, BIOGRAPHY

}
